#!/bin/bash
set -x pipefail
# check for .env and if it doesn't exist, generate one
if [ ! -f ./.env ]; then
  echo '.env does not exist. Generating environnent variables...'
  ./generate-env.sh
fi
# load in the env vars from .env
echo 'Loading environment variables from .env...'
source .env
# generate a new stack.yml from the template
echo 'Generating a stack.yml from template...'
echo '# Warning! Do not edit this file. This file is auto-generated from stack-templates/stack.yml by deploy.sh with env from .env' > stack.yml
echo "# Generated on `date`" >> stack.yml
envsubst < ./stack-templates/stack.yml >> stack.yml
docker stack deploy -c stack.yml nextcloud
